spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/assignment
    username: root
    password: password

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: update
